### ISSUE TITLE
Tame with CoffeeScript?

### ISSUE THREAD

**Issue by mark-hahn** [maxtaco/tamejs#13]
It appears that tame is incompatible with all other trans-compilers like CoffeeScript since other trans-compilers cannot output this ...

```
wait {
    a( defer(b) );
}
```

I have used other trans-compilers piped together before, like CS and Streamline.  In general the wait syntax is very non-JS-like.  I see no reason why tame couldn't use ...

```
wait (
    a( defer(b) );
)
```

This is a shame because I'd really like to try Tame and I've gotten way too spoiled by coffeescript to wear out my fingers writing real JS.

**Comment by michaelficarra** [comment]
https://github.com/maxtaco/tamejs/wiki/Using-tamejs-with-CoffeeScript

**Comment by kav** [comment]
That solution sucks...

**Comment by maxtaco** [comment]
Working on a new approach here:

https://github.com/maxtaco/coffee-script

I got some of the tricky stuff working, but still have a fair amount of work to go.  In particular, CPS translation works, and only is applied to areas of the code that need it.
