### ISSUE TITLE
Preserve JSDoc comments when generating the JS

### ISSUE THREAD

**Issue by bolinfest** [maxtaco/tamejs#22]
Hi, would it be possible to preserve the JSDoc comments from the .tjs file when generating the .js? This would be extremely helpful when running the resulting JS through the Closure Compiler, or other tools that process JSDoc.

Thanks,
Michael

**Comment by maxtaco** [comment]
Good suggestion, I'll see what I can do

**Comment by maxtaco** [comment]
It's pretty hairy given what's currently there.  I think it requires a full reworking of the parser / generator.  I'll hopefully get to that after the coffee script project is completed.
