### ISSUE TITLE
Mixing Sync and Async functions

### ISSUE THREAD

**Issue by debonet** [maxtaco/tamejs#23]
I'm new to TameJS, so I might not know the preferred way to do this. But I'm having difficulty combining synchronous and asynchronous function calls.

Here's what I'd like to be able to do:

await{
    async(function(){console.log("A");defer();});
    async(function(){console.log("B");defer();});
}
console.log("DONE");

Where async is some asynchronous function, such as:

function async(fxn){
    setTimeout(fxn,Math.random()*3000);
}

I'd like to get the output A,B,DONE (or B,A,DONE). But it does not work as expected. Instead I get DONE,A,B (or DONE,B,A).

A second attempt:

await{
    var def=defer();
    var def2=defer();
    async(function(){console.log("A");def();});
    async(function(){console.log("B");def2();});
}
console.log("DONE");

fails with the error:  "ReferenceError: defer is not defined"

However, if I add parens around the defer() calls, it works as desired. e.g.:

await{
    var def=(defer());
    var def2=(defer());
    async(function(){console.log("A");def();});
    async(function(){console.log("B");def2();});
}
console.log("DONE");

It seems the second/parens issue is a problem with the parser. Perhaps its only expecting defer()'s to be used directly within function arguments. 

However, it also seems that the first code could be supportable as well, if the parser could look within subfunctions. Of course, you then have a namespace issue, where you'd need to figure out which await{} a defer() belongs to.  I _think_ it is always unambiguous, since it seems await{} and defer() always happen in the same lexical scope. 

But, perhaps there are some screwball cases where defer() happens elsewhere? if so  perhaps await{} could take a name, e.g.:

await foo {
    async(function(){
        await{
            async(function(){console.log("HERE"); defer());
            foo.defer();
        }
    });
}

(though the above example is unambiguous even without the foo label).

**Comment by maxtaco** [comment]
On Sat, Nov 12, 2011 at 1:07 AM, debonet <
reply@reply.github.com

> wrote:
> 
> I'm new to TameJS, so I might not know the preferred way to do this. But
> I'm having difficulty combining synchronous and asynchronous function calls.
> 
> Here's what I'd like to be able to do:
> 
> await{
>        async(function(){console.log("A");defer();});
>        async(function(){console.log("B");defer();});
> }
> console.log("DONE");

This isn't correct code, since at the very least, you're throwing away what
defer() is returning.  You're going to need those return values, since you
need to fulfill them before the program will continue past the await block.
Your second example makes more sense.  There was a bug in the parser, but
mainly due to your spacing.  var d = defer(); would have worked. Thanks for
the bug report. I'll npm publish what's in the git repo on monday, but it
should be fixed in git now.

It it were me, I would rewrite this as

await {
      delay (function () { console.log ("A"); }, defer ());
      delay (function () { console.log ("B"); }, defer ());
}

and then:

function delay (action, cb) {
    await setTimeout (defer (), 10));
    action();
    cb();
}

**Comment by maxtaco** [comment]
Parse error fixed in d373a33bd32b8 .   Otherwise, leave as is.
