### ISSUE TITLE
vim syntax highlighting

### ISSUE THREAD

**Issue by MSch** [maxtaco/tamejs#25]
I did a quick vim syntax file to highlight `await` and `defer` in `.tjs` files. It's here https://github.com/MSch/vim-tamejs

How about either linking to it from the README or just merging the files in e.g. the `extras/vim` directory.

EDIT: Did some more thinking, people that use e.g. https://github.com/tpope/vim-pathogen won't like having the vim files reside in a subdir.

**Comment by maxtaco** [comment]
Thanks for this Martin!  I'll just go ahead and merge it.

On Sun, Dec 4, 2011 at 3:03 PM, Martin Schrrer <
reply@reply.github.com

**Comment by maxtaco** [comment]
Committed in 944cddd54522e667eaf441afc564635056e1135f; thanks Martin!
