### ISSUE TITLE
Rename twait to something sane

### ISSUE THREAD

**Issue by expensecat** [maxtaco/tamejs#6]
No one wants source code saying twat all over. Call it tame, call it serial, call it await, call it whatever. Just not twat.

**Comment by expensecat** [comment]
mkevent is not better either.

**Comment by maxtaco** [comment]
Thanks for your feedback, I have been agonizing over this.  It is twait/mkevent in the C++ library, so I stuck with it.  Of course have to be careful of keyword clashes.... But await & (future|promise) aren't bad, and in many ways are preferable.

**Comment by maxtaco** [comment]
Checkout the await_and_promise branch, which was a straight find/replace, but still passes all the regtests....

**Comment by expensecat** [comment]
Thanks Max Taco. Sincerely, Expense Cat

**Comment by maxtaco** [comment]
Ok, this is closed.  twait -> await, and mkevent -> defer.
