### ISSUE TITLE
Switch statements seem broken

### ISSUE THREAD

**Issue by felixge** [maxtaco/tamejs#9]
I am having trouble getting simple switch statements to work:

https://gist.github.com/1108773

The parser seems to handle them, but the generated code has trouble executing.

--fg

**Comment by maxtaco** [comment]
Thanks for the Bug report.  I'm pretty sure I fixed that in v0.3.2.  Are you
up-to-date?

**Comment by maxtaco** [comment]
Fixed in v0.3.2

**Comment by felixge** [comment]
Looks like 0.3.2 never made it to the npm registry, and 0.3.3 was just pushed. But yeah, it's fixed now : )

**Comment by maxtaco** [comment]
Burn, I wonder what happened there. I did do `npm publish` as
usual....  Thanks Felix!

On Wed, Jul 27, 2011 at 8:57 AM, felixge
reply@reply.github.com
wrote:
